//document.write("Hello World");
//document.write("私の名前は田中です。");
//document.write("年齢は25歳です。");
//document.write("<h1>あいうえお</h1>");
//document.write("<p>かきくけこ</p>");
//document.write("さしすせそ<br>");
//document.write("月曜日<br>火曜日<br>水曜日");
//alert("別のページに移動します");
//confirm("別のページに移動してもよろしいですか？");
alert("このページを離れようとしています。");
confirm("ログアウトしますか？");